// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8081' | (string & {});
};

/**
 * ContactCreate
 */
export type ContactCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ContactResponse
 */
export type ContactResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Message
     */
    message: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CreateSchedulePayload
 */
export type CreateSchedulePayload = {
    /**
     * Social Media Id
     */
    social_media_id: number;
    /**
     * Recurrence
     */
    recurrence?: number;
    /**
     * Recurrence Unit
     */
    recurrence_unit?: string;
    /**
     * Max Runs
     */
    max_runs?: number;
    /**
     * Scheduled At
     */
    scheduled_at: string;
    /**
     * Prompt
     */
    prompt?: string | null;
};

/**
 * CreateUserPayload
 */
export type CreateUserPayload = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * CreateUserResponse
 */
export type CreateUserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Role
     */
    role: string;
    /**
     * Tier
     */
    tier: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginPayload
 */
export type LoginPayload = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    user: CreateUserResponse;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ScheduleResponse
 */
export type ScheduleResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Social Media Id
     */
    social_media_id: number;
    /**
     * Recurrence
     */
    recurrence: number;
    /**
     * Recurrence Unit
     */
    recurrence_unit: string;
    /**
     * Max Runs
     */
    max_runs: number;
    /**
     * Runs Completed
     */
    runs_completed: number;
    status: ScheduleStatus;
    /**
     * Scheduled At
     */
    scheduled_at: string;
    /**
     * User Timezone
     */
    user_timezone: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Prompt
     */
    prompt: string | null;
};

/**
 * ScheduleStatus
 */
export type ScheduleStatus = 'SCHEDULED' | 'PUBLISHED' | 'FAILED' | 'PENDING' | 'FINISHED';

/**
 * SchedulerLogResponse
 */
export type SchedulerLogResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Scheduler Id
     */
    scheduler_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Post Content
     */
    post_content: string;
    /**
     * Status
     */
    status: string;
    /**
     * Detail
     */
    detail: string | null;
};

/**
 * SocialPlatformStatus
 */
export type SocialPlatformStatus = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Connected
     */
    connected: boolean;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SignupApiV1AuthSignupPostData = {
    body: CreateUserPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup';
};

export type SignupApiV1AuthSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupApiV1AuthSignupPostError = SignupApiV1AuthSignupPostErrors[keyof SignupApiV1AuthSignupPostErrors];

export type SignupApiV1AuthSignupPostResponses = {
    /**
     * Successful Response
     */
    201: CreateUserResponse;
};

export type SignupApiV1AuthSignupPostResponse = SignupApiV1AuthSignupPostResponses[keyof SignupApiV1AuthSignupPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: LoginPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeApiV1AuthMeGetError = MeApiV1AuthMeGetErrors[keyof MeApiV1AuthMeGetErrors];

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: CreateUserResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type LinkedinConnectApiV1SocialMediaConnectLinkedinGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/social-media/connect/linkedin';
};

export type LinkedinConnectApiV1SocialMediaConnectLinkedinGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LinkedinConnectApiV1SocialMediaConnectLinkedinGetError = LinkedinConnectApiV1SocialMediaConnectLinkedinGetErrors[keyof LinkedinConnectApiV1SocialMediaConnectLinkedinGetErrors];

export type LinkedinConnectApiV1SocialMediaConnectLinkedinGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LinkedinCallbackApiV1SocialMediaConnectLinkedinCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/v1/social-media/connect/linkedin/callback';
};

export type LinkedinCallbackApiV1SocialMediaConnectLinkedinCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LinkedinCallbackApiV1SocialMediaConnectLinkedinCallbackGetError = LinkedinCallbackApiV1SocialMediaConnectLinkedinCallbackGetErrors[keyof LinkedinCallbackApiV1SocialMediaConnectLinkedinCallbackGetErrors];

export type LinkedinCallbackApiV1SocialMediaConnectLinkedinCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FacebookConnectApiV1SocialMediaConnectFacebookGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/social-media/connect/facebook';
};

export type FacebookConnectApiV1SocialMediaConnectFacebookGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FacebookConnectApiV1SocialMediaConnectFacebookGetError = FacebookConnectApiV1SocialMediaConnectFacebookGetErrors[keyof FacebookConnectApiV1SocialMediaConnectFacebookGetErrors];

export type FacebookConnectApiV1SocialMediaConnectFacebookGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FacebookCallbackApiV1SocialMediaConnectFacebookCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/v1/social-media/connect/facebook/callback';
};

export type FacebookCallbackApiV1SocialMediaConnectFacebookCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FacebookCallbackApiV1SocialMediaConnectFacebookCallbackGetError = FacebookCallbackApiV1SocialMediaConnectFacebookCallbackGetErrors[keyof FacebookCallbackApiV1SocialMediaConnectFacebookCallbackGetErrors];

export type FacebookCallbackApiV1SocialMediaConnectFacebookCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSocialConnectionStatusApiV1SocialMediaStatusGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/social-media/status';
};

export type GetSocialConnectionStatusApiV1SocialMediaStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSocialConnectionStatusApiV1SocialMediaStatusGetError = GetSocialConnectionStatusApiV1SocialMediaStatusGetErrors[keyof GetSocialConnectionStatusApiV1SocialMediaStatusGetErrors];

export type GetSocialConnectionStatusApiV1SocialMediaStatusGetResponses = {
    /**
     * Response Get Social Connection Status Api V1 Social Media Status Get
     *
     * Successful Response
     */
    200: Array<SocialPlatformStatus>;
};

export type GetSocialConnectionStatusApiV1SocialMediaStatusGetResponse = GetSocialConnectionStatusApiV1SocialMediaStatusGetResponses[keyof GetSocialConnectionStatusApiV1SocialMediaStatusGetResponses];

export type DisconnectSocialPlatformApiV1SocialMediaDisconnectPlatformDeleteData = {
    body?: never;
    path: {
        /**
         * Platform
         */
        platform: string;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/social-media/disconnect/{platform}';
};

export type DisconnectSocialPlatformApiV1SocialMediaDisconnectPlatformDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisconnectSocialPlatformApiV1SocialMediaDisconnectPlatformDeleteError = DisconnectSocialPlatformApiV1SocialMediaDisconnectPlatformDeleteErrors[keyof DisconnectSocialPlatformApiV1SocialMediaDisconnectPlatformDeleteErrors];

export type DisconnectSocialPlatformApiV1SocialMediaDisconnectPlatformDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetScheduleApiV1SchedulerGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/scheduler/';
};

export type GetScheduleApiV1SchedulerGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScheduleApiV1SchedulerGetError = GetScheduleApiV1SchedulerGetErrors[keyof GetScheduleApiV1SchedulerGetErrors];

export type GetScheduleApiV1SchedulerGetResponses = {
    /**
     * Response Get Schedule Api V1 Scheduler  Get
     *
     * Successful Response
     */
    200: Array<ScheduleResponse>;
};

export type GetScheduleApiV1SchedulerGetResponse = GetScheduleApiV1SchedulerGetResponses[keyof GetScheduleApiV1SchedulerGetResponses];

export type CreateScheduleApiV1SchedulerPostData = {
    body: CreateSchedulePayload;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/scheduler/';
};

export type CreateScheduleApiV1SchedulerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScheduleApiV1SchedulerPostError = CreateScheduleApiV1SchedulerPostErrors[keyof CreateScheduleApiV1SchedulerPostErrors];

export type CreateScheduleApiV1SchedulerPostResponses = {
    /**
     * Successful Response
     */
    200: ScheduleResponse;
};

export type CreateScheduleApiV1SchedulerPostResponse = CreateScheduleApiV1SchedulerPostResponses[keyof CreateScheduleApiV1SchedulerPostResponses];

export type GetScheduleApiV1SchedulerGet2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/scheduler';
};

export type GetScheduleApiV1SchedulerGet2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScheduleApiV1SchedulerGet2Error = GetScheduleApiV1SchedulerGet2Errors[keyof GetScheduleApiV1SchedulerGet2Errors];

export type GetScheduleApiV1SchedulerGet2Responses = {
    /**
     * Response Get Schedule Api V1 Scheduler Get
     *
     * Successful Response
     */
    200: Array<ScheduleResponse>;
};

export type GetScheduleApiV1SchedulerGet2Response = GetScheduleApiV1SchedulerGet2Responses[keyof GetScheduleApiV1SchedulerGet2Responses];

export type CreateScheduleApiV1SchedulerPost2Data = {
    body: CreateSchedulePayload;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/scheduler';
};

export type CreateScheduleApiV1SchedulerPost2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScheduleApiV1SchedulerPost2Error = CreateScheduleApiV1SchedulerPost2Errors[keyof CreateScheduleApiV1SchedulerPost2Errors];

export type CreateScheduleApiV1SchedulerPost2Responses = {
    /**
     * Successful Response
     */
    200: ScheduleResponse;
};

export type CreateScheduleApiV1SchedulerPost2Response = CreateScheduleApiV1SchedulerPost2Responses[keyof CreateScheduleApiV1SchedulerPost2Responses];

export type DeleteScheduleApiV1SchedulerScheduleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: number;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/scheduler/{schedule_id}';
};

export type DeleteScheduleApiV1SchedulerScheduleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScheduleApiV1SchedulerScheduleIdDeleteError = DeleteScheduleApiV1SchedulerScheduleIdDeleteErrors[keyof DeleteScheduleApiV1SchedulerScheduleIdDeleteErrors];

export type DeleteScheduleApiV1SchedulerScheduleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteScheduleApiV1SchedulerScheduleIdDeleteResponse = DeleteScheduleApiV1SchedulerScheduleIdDeleteResponses[keyof DeleteScheduleApiV1SchedulerScheduleIdDeleteResponses];

export type GetScheduleLogsApiV1SchedulerScheduleIdLogsGetData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: number;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/scheduler/{schedule_id}/logs';
};

export type GetScheduleLogsApiV1SchedulerScheduleIdLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScheduleLogsApiV1SchedulerScheduleIdLogsGetError = GetScheduleLogsApiV1SchedulerScheduleIdLogsGetErrors[keyof GetScheduleLogsApiV1SchedulerScheduleIdLogsGetErrors];

export type GetScheduleLogsApiV1SchedulerScheduleIdLogsGetResponses = {
    /**
     * Response Get Schedule Logs Api V1 Scheduler  Schedule Id  Logs Get
     *
     * Successful Response
     */
    200: Array<SchedulerLogResponse>;
};

export type GetScheduleLogsApiV1SchedulerScheduleIdLogsGetResponse = GetScheduleLogsApiV1SchedulerScheduleIdLogsGetResponses[keyof GetScheduleLogsApiV1SchedulerScheduleIdLogsGetResponses];

export type UpgradeUserApiV1UsersUpgradePostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/users/upgrade';
};

export type UpgradeUserApiV1UsersUpgradePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpgradeUserApiV1UsersUpgradePostError = UpgradeUserApiV1UsersUpgradePostErrors[keyof UpgradeUserApiV1UsersUpgradePostErrors];

export type UpgradeUserApiV1UsersUpgradePostResponses = {
    /**
     * Successful Response
     */
    200: CreateUserResponse;
};

export type UpgradeUserApiV1UsersUpgradePostResponse = UpgradeUserApiV1UsersUpgradePostResponses[keyof UpgradeUserApiV1UsersUpgradePostResponses];

export type SubmitContactFormApiV1ContactSubmitPostData = {
    body: ContactCreate;
    path?: never;
    query?: never;
    url: '/api/v1/contact/submit';
};

export type SubmitContactFormApiV1ContactSubmitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitContactFormApiV1ContactSubmitPostError = SubmitContactFormApiV1ContactSubmitPostErrors[keyof SubmitContactFormApiV1ContactSubmitPostErrors];

export type SubmitContactFormApiV1ContactSubmitPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ListContactMessagesApiV1ContactListGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/api/v1/contact/list';
};

export type ListContactMessagesApiV1ContactListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListContactMessagesApiV1ContactListGetError = ListContactMessagesApiV1ContactListGetErrors[keyof ListContactMessagesApiV1ContactListGetErrors];

export type ListContactMessagesApiV1ContactListGetResponses = {
    /**
     * Response List Contact Messages Api V1 Contact List Get
     *
     * Successful Response
     */
    200: Array<ContactResponse>;
};

export type ListContactMessagesApiV1ContactListGetResponse = ListContactMessagesApiV1ContactListGetResponses[keyof ListContactMessagesApiV1ContactListGetResponses];
