"""update the task scheduler

Revision ID: 12044f559e4c
Revises: 4729a0709748
Create Date: 2026-07-03 19:57:34.906055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12044f559e4c'
down_revision: Union[str, Sequence[str], None] = '4729a0709748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_scheduler_id'), table_name='task_executions')
    op.create_index(op.f('ix_task_executions_scheduler_id'), 'task_executions', ['scheduler_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_scheduler_id'), table_name='task_executions')
    op.create_index(op.f('ix_task_executions_scheduler_id'), 'task_executions', ['scheduler_id'], unique=True)
    # ### end Alembic commands ###
