"""added_is_verified_column

Revision ID: 152575009883
Revises: cb0f106d52bd
Create Date: 2026-07-19 14:15:05.109123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152575009883'
down_revision: Union[str, Sequence[str], None] = 'cb0f106d52bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True))
    op.execute("UPDATE users SET is_verified = TRUE")
    op.alter_column('users', 'is_verified', nullable=False, server_default='false')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
