"""update the task scheduler

Revision ID: 4729a0709748
Revises: baa5944cef35
Create Date: 2026-07-03 19:33:06.374552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4729a0709748'
down_revision: Union[str, Sequence[str], None] = 'baa5944cef35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler', sa.Column('max_runs', sa.Integer(), nullable=False))
    op.add_column('scheduler', sa.Column('runs_completed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler', 'runs_completed')
    op.drop_column('scheduler', 'max_runs')
    # ### end Alembic commands ###
