"""added timezone support scheduler

Revision ID: 62a50d8617b0
Revises: b49b55e800dc
Create Date: 2026-06-30 18:29:19.781089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a50d8617b0'
down_revision: Union[str, Sequence[str], None] = 'b49b55e800dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler', sa.Column('user_timezone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler', 'user_timezone')
    # ### end Alembic commands ###
