"""added scheduler schema

Revision ID: 7c1ad7ba09b9
Revises: ac9256ec9170
Create Date: 2026-06-28 22:06:24.252724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1ad7ba09b9'
down_revision: Union[str, Sequence[str], None] = 'ac9256ec9170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('social_media_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('recurrence', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['social_media_id'], ['social_media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_social_media_id'), 'scheduler', ['social_media_id'], unique=False)
    op.create_index(op.f('ix_scheduler_user_id'), 'scheduler', ['user_id'], unique=False)
    op.create_index('uq_active_scheduler_per_user_social', 'scheduler', ['user_id', 'social_media_id'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_scheduler_per_user_social', table_name='scheduler', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_scheduler_user_id'), table_name='scheduler')
    op.drop_index(op.f('ix_scheduler_social_media_id'), table_name='scheduler')
    op.drop_table('scheduler')
    # ### end Alembic commands ###
