"""add_parent_id_to_social_media

Revision ID: b4a2003473ca
Revises: 12044f559e4c
Create Date: 2026-07-12 13:39:22.899295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a2003473ca'
down_revision: Union[str, Sequence[str], None] = '12044f559e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'social_media', 'social_media', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_media', type_='foreignkey')
    op.drop_column('social_media', 'parent_id')
    # ### end Alembic commands ###
