"""one-to-one schedule & task

Revision ID: baa5944cef35
Revises: 7cd7da205ee6
Create Date: 2026-07-02 19:19:58.947573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa5944cef35'
down_revision: Union[str, Sequence[str], None] = '7cd7da205ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_scheduler_id'), table_name='task_executions')
    op.create_index(op.f('ix_task_executions_scheduler_id'), 'task_executions', ['scheduler_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_scheduler_id'), table_name='task_executions')
    op.create_index(op.f('ix_task_executions_scheduler_id'), 'task_executions', ['scheduler_id'], unique=False)
    # ### end Alembic commands ###
