"""add reply fields to contact messages

Revision ID: cb0f106d52bd
Revises: 59409dc05fda
Create Date: 2026-07-18 17:36:02.379774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0f106d52bd'
down_revision: Union[str, Sequence[str], None] = '59409dc05fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('is_replied', sa.Boolean(), nullable=False))
    op.add_column('contact_messages', sa.Column('reply_content', sa.Text(), nullable=True))
    op.add_column('contact_messages', sa.Column('replied_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'replied_at')
    op.drop_column('contact_messages', 'reply_content')
    op.drop_column('contact_messages', 'is_replied')
    # ### end Alembic commands ###
