"""added_prompt_logs_recurrence_fields

Revision ID: df01127a2842
Revises: 62a50d8617b0
Create Date: 2026-06-30 20:22:45.524686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df01127a2842'
down_revision: Union[str, Sequence[str], None] = '62a50d8617b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('post_content', sa.String(length=5000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_logs_scheduler_id'), 'scheduler_logs', ['scheduler_id'], unique=False)
    op.add_column('scheduler', sa.Column('recurrence_unit', sa.String(length=20), server_default='days', nullable=False))
    op.add_column('scheduler', sa.Column('prompt', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler', 'prompt')
    op.drop_column('scheduler', 'recurrence_unit')
    op.drop_index(op.f('ix_scheduler_logs_scheduler_id'), table_name='scheduler_logs')
    op.drop_table('scheduler_logs')
    # ### end Alembic commands ###
