"""create api_tokens table

Revision ID: ed0098592115
Revises: e16c2b39b936
Create Date: 2026-06-29 22:36:36.382324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0098592115'
down_revision: Union[str, Sequence[str], None] = 'e16c2b39b936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('social_media_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=2000), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(length=2000), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['social_media_id'], ['social_media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_social_media_id'), 'api_tokens', ['social_media_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_social_media_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
