"""add tier to user

Revision ID: ef3e7e57100b
Revises: 0d705b7489a1
Create Date: 2026-07-16 21:39:03.867646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3e7e57100b'
down_revision: Union[str, Sequence[str], None] = '0d705b7489a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(length=50), server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###
